"""Add NoticeTemplate and update Notice

Revision ID: 7ea8069a7a7a
Revises: 85b6d29f9593
Create Date: 2026-07-18 02:57:59.249925

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ea8069a7a7a'
down_revision: Union[str, None] = '85b6d29f9593'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notice_templates',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('notice_type', sa.Enum('SECTION_94', 'SECTION_168', 'SECTION_106', 'UNFREEZE_ORDER', 'CLARIFICATION', name='noticetypeenum', native_enum=False), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content_template', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('signed_off_by_name', sa.String(length=255), nullable=True),
    sa.Column('signed_off_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notice_templates_notice_type'), 'notice_templates', ['notice_type'], unique=False)
    op.add_column('notices', sa.Column('template_version', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notices', 'template_version')
    op.drop_index(op.f('ix_notice_templates_notice_type'), table_name='notice_templates')
    op.drop_table('notice_templates')
    # ### end Alembic commands ###
