"""Add closure fields to Case

Revision ID: 8067d7939fac
Revises: 7ea8069a7a7a
Create Date: 2026-07-18 03:04:30.790994

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8067d7939fac'
down_revision: Union[str, None] = '7ea8069a7a7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('closure_reason', sa.String(length=100), nullable=True))
    op.add_column('cases', sa.Column('closure_remarks', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'closure_remarks')
    op.drop_column('cases', 'closure_reason')
    # ### end Alembic commands ###
