"""phase_12_risk_scoring

Revision ID: 85b6d29f9593
Revises: d30d68b885eb
Create Date: 2026-07-18 02:28:12.701384

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85b6d29f9593'
down_revision: Union[str, None] = 'd30d68b885eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('risk_score', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('accounts', sa.Column('risk_explanation_json', sa.JSON(), nullable=True))
    op.alter_column('accounts', 'cash_out_detected',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_accounts_layer_number'), table_name='accounts')
    op.create_index(op.f('ix_accounts_bank_name'), 'accounts', ['bank_name'], unique=False)
    op.create_index(op.f('ix_accounts_risk_score'), 'accounts', ['risk_score'], unique=False)
    op.create_index(op.f('ix_accounts_wallet_id'), 'accounts', ['wallet_id'], unique=False)
    op.alter_column('cases', 'fraud_category',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('DIGITAL_ARREST', 'INVESTMENT_SCAM', 'ONLINE_TRADING_SCAM', 'HACKING_DIGITAL_FRAUD', 'SEXTORTION', 'OTHER', name='fraudcategoryenum', native_enum=False),
               existing_nullable=False)
    op.alter_column('cases', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('REPORTED', 'INTAKE_COMPLETE', 'TRACING', 'NOTICE_PENDING', 'NOTICE_SENT', 'AWAITING_BANK', 'ACTION_TAKEN', 'PARTIALLY_RECOVERED', 'CLOSED', 'DEAD_END', name='casestatusenum', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'intake_complete'::character varying"))
    op.create_index(op.f('ix_evidences_uploaded_by_user_id'), 'evidences', ['uploaded_by_user_id'], unique=False)
    op.create_index(op.f('ix_import_jobs_uploaded_by_user_id'), 'import_jobs', ['uploaded_by_user_id'], unique=False)
    op.alter_column('notices', 'notice_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('SECTION_94', 'SECTION_168', 'SECTION_106', 'UNFREEZE_ORDER', 'CLARIFICATION', name='noticetypeenum', native_enum=False),
               existing_nullable=False)
    op.alter_column('notices', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('DRAFTED', 'SENT', 'ACKNOWLEDGED', 'ACTION_TAKEN', 'OVERDUE', 'REJECTED', 'CLARIFICATION_REQUESTED', name='noticestatusenum', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'drafted'::character varying"))
    op.create_index(op.f('ix_notices_issued_by_user_id'), 'notices', ['issued_by_user_id'], unique=False)
    op.create_index(op.f('ix_notices_recipient_bank_ifsc'), 'notices', ['recipient_bank_ifsc'], unique=False)
    op.create_index(op.f('ix_notices_recipient_bank_name'), 'notices', ['recipient_bank_name'], unique=False)
    op.create_index(op.f('ix_notifications_case_id'), 'notifications', ['case_id'], unique=False)
    op.create_index(op.f('ix_notifications_notice_id'), 'notifications', ['notice_id'], unique=False)
    op.alter_column('templates', 'notice_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('SECTION_94', 'SECTION_168', 'SECTION_106', 'UNFREEZE_ORDER', 'CLARIFICATION', name='noticetypeenum', native_enum=False),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('OFFICER', 'SUPERVISOR', 'ADMIN', name='roleenum', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'officer'::character varying"))
    op.create_index(op.f('ix_watchlist_entries_added_by_user_id'), 'watchlist_entries', ['added_by_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_entries_added_by_user_id'), table_name='watchlist_entries')
    op.alter_column('users', 'role',
               existing_type=sa.Enum('OFFICER', 'SUPERVISOR', 'ADMIN', name='roleenum', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'officer'::character varying"))
    op.alter_column('templates', 'notice_type',
               existing_type=sa.Enum('SECTION_94', 'SECTION_168', 'SECTION_106', 'UNFREEZE_ORDER', 'CLARIFICATION', name='noticetypeenum', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_notifications_notice_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_case_id'), table_name='notifications')
    op.drop_index(op.f('ix_notices_recipient_bank_name'), table_name='notices')
    op.drop_index(op.f('ix_notices_recipient_bank_ifsc'), table_name='notices')
    op.drop_index(op.f('ix_notices_issued_by_user_id'), table_name='notices')
    op.alter_column('notices', 'status',
               existing_type=sa.Enum('DRAFTED', 'SENT', 'ACKNOWLEDGED', 'ACTION_TAKEN', 'OVERDUE', 'REJECTED', 'CLARIFICATION_REQUESTED', name='noticestatusenum', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'drafted'::character varying"))
    op.alter_column('notices', 'notice_type',
               existing_type=sa.Enum('SECTION_94', 'SECTION_168', 'SECTION_106', 'UNFREEZE_ORDER', 'CLARIFICATION', name='noticetypeenum', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_import_jobs_uploaded_by_user_id'), table_name='import_jobs')
    op.drop_index(op.f('ix_evidences_uploaded_by_user_id'), table_name='evidences')
    op.alter_column('cases', 'status',
               existing_type=sa.Enum('REPORTED', 'INTAKE_COMPLETE', 'TRACING', 'NOTICE_PENDING', 'NOTICE_SENT', 'AWAITING_BANK', 'ACTION_TAKEN', 'PARTIALLY_RECOVERED', 'CLOSED', 'DEAD_END', name='casestatusenum', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'intake_complete'::character varying"))
    op.alter_column('cases', 'fraud_category',
               existing_type=sa.Enum('DIGITAL_ARREST', 'INVESTMENT_SCAM', 'ONLINE_TRADING_SCAM', 'HACKING_DIGITAL_FRAUD', 'SEXTORTION', 'OTHER', name='fraudcategoryenum', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_accounts_wallet_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_risk_score'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_bank_name'), table_name='accounts')
    op.create_index(op.f('ix_accounts_layer_number'), 'accounts', ['layer_number'], unique=False)
    op.alter_column('accounts', 'cash_out_detected',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('accounts', 'risk_explanation_json')
    op.drop_column('accounts', 'risk_score')
    # ### end Alembic commands ###
